name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update dependencies
        run: |
          # Update all dependencies to latest
          pnpm update --latest
          
          # Update devDependencies
          pnpm update --latest --dev

      - name: Run tests to ensure updates work
        run: |
          pnpm run check
          pnpm run test
          pnpm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies to latest versions'
          title: '📦 Update Dependencies'
          body: |
            ## Dependency Updates
            
            This PR updates all dependencies to their latest versions.
            
            ### What's Changed
            - Updated all production dependencies
            - Updated all development dependencies
            - All tests pass with updated dependencies
            
            ### Verification
            - ✅ Tests pass
            - ✅ Build succeeds
            - ✅ Linting passes
            
            **Auto-generated by GitHub Actions** 🤖
          branch: dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated